version: "3.0"
services:
  frontend:
    image: itsmebunny/employee-board:latest
    container_name: react
    stdin_open: true
    ports:
      - "3000:3000"

  nodejs:
    image: itsmebunny/employee-board:latest
    container_name: nodejs
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"